version: '3.9'

services:
  db:
    container_name: postgres 
    image: postgres:14-alpine
    restart: "${DOCKER_RESTART_POLICY:-unless-stopped}"
    environment:
    - POSTGRES_PASSWORD:
    - POSTGRES_USER:
    ports:
      - 5432:5432
    volumes:
      - data:/var/lib/postgres/data

volumes:
  data: {}
